repos:
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        language: python
        entry: yamllint
        args: [-c, .yamllint.yml]
        types: [yaml]
        additional_dependencies: [yamllint]
